In [4]:
import numpy as np
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.datasets import load_files
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from gensim.models import Word2Vec
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from gensim.models import KeyedVectors
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences 
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, SimpleRNN
from keras.layers import Dense, Dropout, Activation
from keras.layers import Conv1D, MaxPooling1D
from keras.utils.np_utils import to_categorical
from keras.models import Model
from tensorflow.keras import Input

In [22]:
%%time
import os
from glob import glob
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns
import re
import nltk
import json
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, ExtraTreesClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
from sklearn.metrics import average_precision_score,roc_auc_score, roc_curve, precision_recall_curve
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
np.random.seed(42)
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.tokenize import ToktokTokenizer
import nltk, string, re, spacy,unicodedata, random
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings('ignore')
### Pretrained Word Embeddings

folder_path = "/content/drive/MyDrive/model_imp_NLP"

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


CPU times: user 1.98 s, sys: 411 ms, total: 2.39 s
Wall time: 5.75 s


# NLTK experiments

In [88]:
text = 'NLP is a subfield of computer science and artificial intelligence. It is concerned with interactions between computers and human (natural) languages. It is used to apply machine learning algorithms to text and speech.'

In [89]:
print(text)

NLP is a subfield of computer science and artificial intelligence. It is concerned with interactions between computers and human (natural) languages. It is used to apply machine learning algorithms to text and speech.


In [90]:
#Sentence tokenization. Splitting the paragraph into sentences
sentences = sent_tokenize(text)
print(sentences)

['NLP is a subfield of computer science and artificial intelligence.', 'It is concerned with interactions between computers and human (natural) languages.', 'It is used to apply machine learning algorithms to text and speech.']


In [91]:
#Word tokenization. Splitting the sentences into words
words = word_tokenize(text)
print(words)

['NLP', 'is', 'a', 'subfield', 'of', 'computer', 'science', 'and', 'artificial', 'intelligence', '.', 'It', 'is', 'concerned', 'with', 'interactions', 'between', 'computers', 'and', 'human', '(', 'natural', ')', 'languages', '.', 'It', 'is', 'used', 'to', 'apply', 'machine', 'learning', 'algorithms', 'to', 'text', 'and', 'speech', '.']


In [92]:
#Sentence wise word tokenization 
tokenized_words = []

for i in range(len(sentences)):
    tokenized_words.append(word_tokenize(sentences[i]))

print(tokenized_words)

[['NLP', 'is', 'a', 'subfield', 'of', 'computer', 'science', 'and', 'artificial', 'intelligence', '.'], ['It', 'is', 'concerned', 'with', 'interactions', 'between', 'computers', 'and', 'human', '(', 'natural', ')', 'languages', '.'], ['It', 'is', 'used', 'to', 'apply', 'machine', 'learning', 'algorithms', 'to', 'text', 'and', 'speech', '.']]


In [93]:
#Stemming
stemmer = PorterStemmer()
stemmed_sent = []

for i in range(len(sentences)):
    words = word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words]
    stemmed_sent.append(words) 

print(stemmed_sent)

[['nlp', 'is', 'a', 'subfield', 'of', 'comput', 'scienc', 'and', 'artifici', 'intellig', '.'], ['it', 'is', 'concern', 'with', 'interact', 'between', 'comput', 'and', 'human', '(', 'natur', ')', 'languag', '.'], ['it', 'is', 'use', 'to', 'appli', 'machin', 'learn', 'algorithm', 'to', 'text', 'and', 'speech', '.']]


In [95]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [96]:
#Lemmatization
lemmatizer = WordNetLemmatizer()
lemma_sent = []

for i in range(len(sentences)):
    words = word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words]
    lemma_sent.append(words)
    
print(lemma_sent)

LookupError: ignored

In [97]:
#Print stop words in English
stops = stopwords.words("english")
print(stops)

LookupError: ignored

In [ ]:
#Removing stop words
stop_words_removed = []

for i in range(len(sentences)):
    words = word_tokenize(sentences[i])
    words = [word for word in words if word not in stopwords.words('english')]
    stop_words_removed.append(words)
    
print(stop_words_removed)

[['NLP', 'subfield', 'computer', 'science', 'artificial', 'intelligence', '.'], ['It', 'concerned', 'interactions', 'computers', 'human', '(', 'natural', ')', 'languages', '.'], ['It', 'used', 'apply', 'machine', 'learning', 'algorithms', 'text', 'speech', '.']]


# Text classification
## Sentiment analysis

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [14]:
#Reading the data
data = pd.read_excel('/content/drive/MyDrive/model_imp_NLP/be_data_no_un_combined.xlsx')

In [15]:
data.head()

Label                                               Text
0  Disgust   Dakhachish ai to tui svf are chala..to jeet d...
1  Disgust  Romantic comedy te je kikore eto vulgar jinish...
2  Sadness  Shokal thake burger r grill khaite mon chai bu...
3      Joy   jakhon dekhbi banglar chhele-meye banglay par...
4  Disgust  Mymensingh er manush eto kharap kn : ( na obos...

In [17]:
# #Preprocessing - removing unwanted characters, tokenization, stop-word removal
# def clean_data(tweet):
#     x = re.sub("[^a-zA-Z0-9]", " ",tweet) 
#     x = x.lower().split()                             
#     stops = set(stopwords.words("english"))                  
#     words = [w for w in x if not w in stops] 
#     return( " ".join(words)) 

In [ ]:
# data['text'] = data['text'].apply(lambda x: clean_data(x))
# print(data['text'])

0        nancyleegrahn everyone feel climate change que...
1        scottwalker catch full gopdebate last night sc...
2        tjmshow mention tamir rice gopdebate held clev...
3        robgeorge carly fiorina trending hours debate ...
4        danscavino gopdebate w realdonaldtrump deliver...
5        gregabbott tx tedcruz first day rescind every ...
6        warriorwoman91 liked happy heard going moderat...
7        going msnbc live thomasaroberts around 2 pm et...
8        deer headlights lizzwinstead ben carson may br...
9        nancyosborne180 last night debate proved gopde...
10       jgreendc realdonaldtrump fairness billclinton ...
11       waynedupreeshow woke tweet gopdebate best line...
12       reading family comments great gopdebate http c...
13       arcticfox2016 allenwestrepub dear jebbush gopd...
14       pattonoswalt loved scott walker mark harmon ro...
15       hey chrischristie exploiting tragedy 9 11 poli...
16       carolcnn donaldtrump fire comments women peter.

In [ ]:
# for i in range(len(data)):
#     data['text'][i] = data['text'][i].replace('rt ','')

# print(data['text'])

0        nancyleegrahn everyone feel climate change que...
1        scottwalker catch full gopdebate last night sc...
2        tjmshow mention tamir rice gopdebate held clev...
3        robgeorge carly fiorina trending hours debate ...
4        danscavino gopdebate w realdonaldtrump deliver...
5        gregabbott tx tedcruz first day rescind every ...
6        warriorwoman91 liked happy heard going moderat...
7        going msnbc live thomasaroberts around 2 pm et...
8        deer headlights lizzwinstead ben carson may br...
9        nancyosborne180 last night debate proved gopde...
10       jgreendc realdonaldtrump fairness billclinton ...
11       waynedupreeshow woke tweet gopdebate best line...
12       reading family comments great gopdebate http c...
13       arcticfox2016 allenwestrepub dear jebbush gopd...
14       pattonoswalt loved scott walker mark harmon ro...
15       hey chrischristie exploiting tragedy 9 11 poli...
16       carolcnn donaldtrump fire comments women peter.

In [18]:
'''
Text Cleaning
'''
def text_cleaning(row):
  # to remove HTML tags
  text = BeautifulSoup(row, 'html.parser').get_text()
  d = re.sub(r'(https|http)?:\/\/(\w|\.|\/|\?|\=|\&|\%)*\b', '', text, flags=re.MULTILINE) #This line is for removing url
  post = d.replace('\n', '')
  post = post.replace('—', ' ')
  # to remove accented characters
  new_text = unicodedata.normalize('NFKD', post).encode('ascii', 'ignore').decode('utf-8', 'ignore')
  # to remove special characters and numbers
  # define the pattern to keep
  #pat = r'[^a-zA-z0-9.,!?/:;\"\'\s]' 
  #text = re.sub(pat, '', new_text)
  #to remove punctuation
  text = ''.join([c for c in text if c not in string.punctuation])
  # to remove special characters
  pattern = r'^\s*|\s\s*'
  text = re.sub(pattern, ' ', text).strip()
  # convert into lower case
  text = text.lower() 
  # Stopword Removing
  tokenizer = ToktokTokenizer()
  # convert sentence into token of words
  tokens = tokenizer.tokenize(text)
  tokens = [token.strip() for token in tokens]
  # check in lowercase 
  #t = [token for token in tokens if token.lower() not in stopword_list]
  #text = ' '.join(t) 
  # Stemming
  #t = [stemming.stem(token) for token in tokens ]
  #text = ' '.join(t) 

  return text

In [19]:
def get_becodemixed_stop_words():
    #swdf1 = pd.read_csv("/content/drive/MyDrive/automated_tamil_text_classification-master/data/TamilNLP_TamilStopWords.txt",  header=None) 
    swdf2 = pd.read_csv("/content/drive/MyDrive/mode_imp_AED 25GPU/custom_becodemixed_stopwords.txt",  header=None) 
    #sw1 = swdf1[0].tolist()
    sw2 = swdf2[0].tolist()
    #tamil_stop_words = list(set(sw1 + sw2))
    becodemixed_stop_words = list(sw2)
    return becodemixed_stop_words

In [24]:
becodemixed_stop_words = get_becodemixed_stop_words()
data['Texts'] = data['Text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (becodemixed_stop_words)]))



data['cleaned'] = data['Texts'].apply(text_cleaning)



## Data samples after cleaning
print("Original Data:===\n",data.Text[0],"\nCleaned Data:===\n",data.cleaned[0],)

Original Data:===
  Dakhachish ai to tui svf are chala..to jeet dar collection to fake blban e to ... sir manush boka noi 
Cleaned Data:===
 dakhachish tui svf are chalato jeet dar collection fake blban sir manush boka noi


In [25]:
#Converting the dataframe into list
reviews = data['Text'].tolist()
sentiment = data['Label'].tolist()

In [26]:
corpus = []
for i in range(len(reviews)):
    corpus.append(word_tokenize(reviews[i]))

In [27]:
corpus

[['Dakhachish',
  'ai',
  'to',
  'tui',
  'svf',
  'are',
  'chala',
  '..',
  'to',
  'jeet',
  'dar',
  'collection',
  'to',
  'fake',
  'blban',
  'e',
  'to',
  '...',
  'sir',
  'manush',
  'boka',
  'noi'],
 ['Romantic',
  'comedy',
  'te',
  'je',
  'kikore',
  'eto',
  'vulgar',
  'jinish',
  'potro',
  'dhokalo',
  ',',
  'hall',
  'e',
  'toh',
  'shobai',
  'was',
  'embarrassed',
  '.'],
 ['Shokal',
  'thake',
  'burger',
  'r',
  'grill',
  'khaite',
  'mon',
  'chai',
  'but',
  'ohh',
  'nah',
  'amr',
  'paa',
  'niya',
  'ber',
  'hoite',
  'parbona',
  ':',
  "'",
  ')',
  'cause',
  'suye',
  'thaka',
  'chara',
  'kaj',
  'nai',
  'r'],
 ['jakhon',
  'dekhbi',
  'banglar',
  'chhele-meye',
  'banglay',
  'para',
  'sonar',
  'korar',
  'par',
  'banglay',
  'kaaj',
  'peye',
  'jachhe',
  'takhon',
  'bhabis',
  'Bangla',
  'egochhe',
  'bujhli'],
 ['Mymensingh',
  'er',
  'manush',
  'eto',
  'kharap',
  'kn',
  ':',
  '(',
  'na',
  'obosshoi',
  'shobai',
  'na

### Feature extraction using word2vec

In [28]:
#Creating word embedding for the words. Embedding dimension = 100
model = Word2Vec(corpus, size=100, window=5, min_count=1)

In [29]:
#Voabulary list
model.wv.vocab

{'Dakhachish': <gensim.models.keyedvectors.Vocab at 0x7f99c271bc90>,
 'ai': <gensim.models.keyedvectors.Vocab at 0x7f99c271bf10>,
 'to': <gensim.models.keyedvectors.Vocab at 0x7f99c271be50>,
 'tui': <gensim.models.keyedvectors.Vocab at 0x7f99c271bf50>,
 'svf': <gensim.models.keyedvectors.Vocab at 0x7f99c2768b90>,
 'are': <gensim.models.keyedvectors.Vocab at 0x7f99c2768a50>,
 'chala': <gensim.models.keyedvectors.Vocab at 0x7f99c2768690>,
 '..': <gensim.models.keyedvectors.Vocab at 0x7f99c2768490>,
 'jeet': <gensim.models.keyedvectors.Vocab at 0x7f99c271ba90>,
 'dar': <gensim.models.keyedvectors.Vocab at 0x7f99c2768110>,
 'collection': <gensim.models.keyedvectors.Vocab at 0x7f99c2768cd0>,
 'fake': <gensim.models.keyedvectors.Vocab at 0x7f99c27680d0>,
 'blban': <gensim.models.keyedvectors.Vocab at 0x7f99c2768fd0>,
 'e': <gensim.models.keyedvectors.Vocab at 0x7f99c2768290>,
 '...': <gensim.models.keyedvectors.Vocab at 0x7f99c2768e50>,
 'sir': <gensim.models.keyedvectors.Vocab at 0x7f99c276

In [30]:
#Word embedding of the word "With"
model.wv["level"]

array([ 0.01810701,  0.01591623, -0.19145988,  0.00714305,  0.03583377,
       -0.04456915,  0.00925641, -0.01456909, -0.03298774,  0.0775524 ,
        0.04085288,  0.05046859,  0.05023065, -0.05531529,  0.01073352,
        0.04522188, -0.01316367, -0.09168622, -0.03272127,  0.0183925 ,
       -0.07539435,  0.17215908,  0.0075663 ,  0.08927865,  0.10723541,
        0.13536215, -0.13271858,  0.10773879, -0.05677692, -0.15570171,
        0.11190748,  0.01448994, -0.02016269,  0.04139496, -0.04077546,
        0.06532578,  0.02135529, -0.07001461,  0.04890126, -0.01503238,
       -0.00238972, -0.02026743,  0.00561681, -0.07642833,  0.04078541,
       -0.05021708,  0.02123763, -0.10214202,  0.05501987,  0.02189064,
        0.04105949, -0.04383132,  0.05757936, -0.09990934,  0.02984949,
        0.09291268,  0.00370135,  0.02732687, -0.03806002,  0.00860314,
        0.06764553, -0.07061133, -0.07600464,  0.05462908,  0.05332767,
        0.00316914,  0.03324176, -0.04823458,  0.0011246 ,  0.04

In [31]:
#Simialr words of music in the corpus
model.wv.most_similar("level")

[('ta', 0.9989065527915955),
 ('eto', 0.9988089799880981),
 ('ekta', 0.9988064765930176),
 (',', 0.9988021850585938),
 ('tate', 0.9987781047821045),
 ('je', 0.9987627267837524),
 ('khub', 0.9987595081329346),
 ('movie', 0.9987587332725525),
 ('laglo', 0.9987377524375916),
 ('eta', 0.9987372756004333)]

In [38]:
model.wv.most_similar(positive=['bhalo','khushi'], negative= ['kharap'], topn=5)

[('lagche', 0.9986018538475037),
 ('kobe', 0.9985663890838623),
 ('amar', 0.9985489845275879),
 ('you', 0.9985064268112183),
 ('hote', 0.9985044002532959)]

In [39]:
model.wv.doesnt_match(['bhalo','kharap','khushi','movie'])

'khushi'

In [41]:
#Creating the input data
X = np.zeros((len(corpus),100)) #Initializing the X matrix with zeros
for i in range(len(corpus)):
    emb = [model.wv[w] for w in corpus[i]] #Create a list of word embeddings of the words in each sentence
    X[i] = np.mean(emb, axis=0) #Take the mean of the word embeddings of the words in a sentence because length of the sentences varies and the dimension of the features will increase with the increase in the number of words in the sentence

In [43]:
le = preprocessing.LabelEncoder()
Y = le.fit_transform(sentiment)

In [44]:
print(X.shape,Y.shape)

(5067, 100) (5067,)


In [46]:
#Splitting the data into train data and test data
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.20, random_state = 42)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(4053, 100) (4053,)
(1014, 100) (1014,)


In [47]:
#Printing the size of the train data, train label, test data and test label
print("Shape train data = ",np.shape(X_train))
print("Shape of train label = ",np.shape(y_train))
print("Shape of test data = ",np.shape(X_test))
print("Shape of test label = ",np.shape(y_test))

Shape train data =  (4053, 100)
Shape of train label =  (4053,)
Shape of test data =  (1014, 100)
Shape of test label =  (1014,)


In [48]:
#Classification using SVM
clf = GaussianNB() #Initializing the classifier
clf.fit(X_train, y_train) #Train the classifier using X_train and y_train

GaussianNB()

In [49]:
#Predict the class label for the test data using the trained model
y_pred = clf.predict(X_test)

In [50]:
#Generating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[39 28 26  0  6 29]
 [37 52 29  5  9 65]
 [19 16 15  0  4 24]
 [78 75 55  5 26 85]
 [39 63 45  1 26 50]
 [10 21  8  1  3 20]]


In [51]:
#Computation of the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy = ','%.2f'%(accuracy*100))

Accuracy =  15.48


In [53]:
#K-fold cross-validation
score = cross_val_score(clf, X, Y, cv = 5)

In [54]:
#Performance of the model evaluated using accuracy score. k-fold cross-validation gives k different accuracy score. 
#Hence the accuracy of prediction by the model is taken as the mean of the accuracy score +/- standard deviation of the score
print('Accuracy = ','%.2f'%(np.mean(score)*100),"+/-",'%.4f'%(np.std(score)))

Accuracy =  15.00 +/- 0.0136


### Feature extraction using Doc2vec

In [55]:
#Creating sentence embedding with Doc2vec
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(corpus)]
model = Doc2Vec(documents, size = 100, window=5, min_count=1)

In [56]:
#Create the input matrix using doc2vec embeddings
X = []

for i in range(len(corpus)):
    X.append(model.infer_vector(corpus[i]))

In [58]:
#Splitting the data into train data and test data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [59]:
#Printing the size of the train data, train label, test data and test label
print("Shape train data = ",np.shape(X_train))
print("Shape of train label = ",np.shape(y_train))
print("Shape of test data = ",np.shape(X_test))
print("Shape of test label = ",np.shape(y_test))

Shape train data =  (4053, 100)
Shape of train label =  (4053,)
Shape of test data =  (1014, 100)
Shape of test label =  (1014,)


In [60]:
#Classification using SVM
clf = GaussianNB() #Initializing the classifier
clf.fit(X_train, y_train) #Train the classifier using X_train and y_train

GaussianNB()

In [61]:
#Predict the class label for the test data using the trained model
y_pred = clf.predict(X_test)

In [62]:
#Generating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 12   6  84   0   4  22]
 [ 19  21 103   1  11  42]
 [  1   5  63   0   1   8]
 [ 29  48 151   5  17  74]
 [ 25  16 121   2  16  44]
 [  4   9  29   1   3  17]]


In [63]:
#Computation of the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy = ','%.2f'%(accuracy*100))

Accuracy =  13.21


In [64]:
#K-fold cross-validation
score = cross_val_score(clf, X, sentiment, cv = 5)

In [65]:
#Performance of the model evaluated using accuracy score. k-fold cross-validation gives k different accuracy score. 
#Hence the accuracy of prediction by the model is taken as the mean of the accuracy score +/- standard deviation of the score
print('Accuracy = ','%.2f'%(np.mean(score)*100),"+/-",'%.4f'%(np.std(score)))

Accuracy =  13.16 +/- 0.0108


### Feature extraction using pretrained models

In [71]:
import gensim
from gensim.models import word2vec
from gensim.models import KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity

In [72]:
!wget -P /root/input/ -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2022-06-22 14:34:04--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.106.222
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.106.222|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 94 [application/x-gzip]
Saving to: ‘/root/input/GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]      94  --.-KB/s    in 0s      

2022-06-22 14:34:04 (4.03 MB/s) - ‘/root/input/GoogleNews-vectors-negative300.bin.gz’ saved [94/94]



In [98]:
EMBEDDING_FILE = '/root/input/GoogleNews-vectors-negative300.bin.gz'
word_vectors = KeyedVectors.load_word2vec_format(EMBEDDING_FILE, binary=True)

ValueError: ignored

In [ ]:
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

In [78]:
model.wv.most_similar(positive=['bhalo','khushi'], negative= ['kharap'], topn=1)

[('valo', 0.9988052845001221)]

## Text classification using deep learning algorithms

In [79]:
data = pd.read_excel('/content/drive/MyDrive/model_imp_NLP/be_data_no_un_combined.xlsx')

In [80]:
data.head()

Label                                               Text
0  Disgust   Dakhachish ai to tui svf are chala..to jeet d...
1  Disgust  Romantic comedy te je kikore eto vulgar jinish...
2  Sadness  Shokal thake burger r grill khaite mon chai bu...
3      Joy   jakhon dekhbi banglar chhele-meye banglay par...
4  Disgust  Mymensingh er manush eto kharap kn : ( na obos...

In [81]:
# #Preprocessing - removing unwanted characters, tokenization, stop-word removal
# def clean_data(tweet):
#     x = re.sub("[^a-zA-Z0-9]", " ",tweet) 
#     x = x.lower().split()                             
#     stops = set(stopwords.words("english"))                  
#     words = [w for w in x if not w in stops] 
#     return( " ".join(words)) 

In [ ]:
# data['text'] = data['text'].apply(lambda x: clean_data(x))

In [ ]:
# for i in range(len(data)):
#     data['text'][i] = data['text'][i].replace('rt ','')

In [83]:
'''
Text Cleaning
'''
def text_cleaning(row):
  # to remove HTML tags
  text = BeautifulSoup(row, 'html.parser').get_text()
  d = re.sub(r'(https|http)?:\/\/(\w|\.|\/|\?|\=|\&|\%)*\b', '', text, flags=re.MULTILINE) #This line is for removing url
  post = d.replace('\n', '')
  post = post.replace('—', ' ')
  # to remove accented characters
  new_text = unicodedata.normalize('NFKD', post).encode('ascii', 'ignore').decode('utf-8', 'ignore')
  # to remove special characters and numbers
  # define the pattern to keep
  #pat = r'[^a-zA-z0-9.,!?/:;\"\'\s]' 
  #text = re.sub(pat, '', new_text)
  #to remove punctuation
  text = ''.join([c for c in text if c not in string.punctuation])
  # to remove special characters
  pattern = r'^\s*|\s\s*'
  text = re.sub(pattern, ' ', text).strip()
  # convert into lower case
  text = text.lower() 
  # Stopword Removing
  tokenizer = ToktokTokenizer()
  # convert sentence into token of words
  tokens = tokenizer.tokenize(text)
  tokens = [token.strip() for token in tokens]
  # check in lowercase 
  #t = [token for token in tokens if token.lower() not in stopword_list]
  #text = ' '.join(t) 
  # Stemming
  #t = [stemming.stem(token) for token in tokens ]
  #text = ' '.join(t) 

  return text

In [84]:
def get_becodemixed_stop_words():
    #swdf1 = pd.read_csv("/content/drive/MyDrive/automated_tamil_text_classification-master/data/TamilNLP_TamilStopWords.txt",  header=None) 
    swdf2 = pd.read_csv("/content/drive/MyDrive/mode_imp_AED 25GPU/custom_becodemixed_stopwords.txt",  header=None) 
    #sw1 = swdf1[0].tolist()
    sw2 = swdf2[0].tolist()
    #tamil_stop_words = list(set(sw1 + sw2))
    becodemixed_stop_words = list(sw2)
    return becodemixed_stop_words

In [85]:
becodemixed_stop_words = get_becodemixed_stop_words()
data['Texts'] = data['Text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (becodemixed_stop_words)]))



data['cleaned'] = data['Texts'].apply(text_cleaning)



## Data samples after cleaning
print("Original Data:===\n",data.Text[0],"\nCleaned Data:===\n",data.cleaned[0],)

Original Data:===
  Dakhachish ai to tui svf are chala..to jeet dar collection to fake blban e to ... sir manush boka noi 
Cleaned Data:===
 dakhachish tui svf are chalato jeet dar collection fake blban sir manush boka noi


In [86]:
#Converting the dataframe into list
reviews = data['Text'].tolist()
sentiment = data['Label'].tolist()

corpus = []
for i in range(len(reviews)):
    corpus.append(word_tokenize(reviews[i]))

In [100]:
#Tokenization
max_features = 1200 #number of words to keep. 1200 is the number of unique words in the corpus.
tokenizer = Tokenizer(nb_words=max_features, split=' ')
tokenizer.fit_on_texts(data['Text'].values)

In [101]:
#Unique words and and their count
tokenizer.word_counts

OrderedDict([('dakhachish', 1),
             ('ai', 51),
             ('to', 443),
             ('tui', 102),
             ('svf', 2),
             ('are', 53),
             ('chala', 1),
             ('jeet', 33),
             ('dar', 17),
             ('collection', 13),
             ('fake', 8),
             ('blban', 1),
             ('e', 773),
             ('sir', 68),
             ('manush', 287),
             ('boka', 23),
             ('noi', 14),
             ('romantic', 20),
             ('comedy', 30),
             ('te', 189),
             ('je', 514),
             ('kikore', 6),
             ('eto', 302),
             ('vulgar', 5),
             ('jinish', 15),
             ('potro', 3),
             ('dhokalo', 1),
             ('hall', 53),
             ('toh', 155),
             ('shobai', 137),
             ('was', 151),
             ('embarrassed', 1),
             ('shokal', 14),
             ('thake', 54),
             ('burger', 2),
             ('r', 453),
     

In [103]:
#Dictionary index of a word
tokenizer.word_index["shundor"]

209

In [104]:
X = tokenizer.texts_to_sequences(data['Text'].values)
X = pad_sequences(X, padding = 'post') #Zero padding at the end of the sequence

In [105]:
Y = to_categorical(Y)
print(Y)

[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [106]:
#Splitting the data into train data and test data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

### RNN, LSTM, Stacked-RNN, Stacked-LSTM, Bidirectional-RNN, Bidirectional-LSTM

In [133]:
embed_dim = 500
hidden_layer = 100

model = Sequential()
model.add(Embedding(max_features, embed_dim,input_length = X.shape[1]))
model.add(Dropout(0.2))
model.add(SimpleRNN(hidden_layer))
model.add(Dense(6,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 79, 500)           600000    
                                                                 
 dropout_3 (Dropout)         (None, 79, 500)           0         
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 100)               60100     
                                                                 
 dense_4 (Dense)             (None, 6)                 606       
                                                                 
Total params: 660,706
Trainable params: 660,706
Non-trainable params: 0
_________________________________________________________________
None


In [134]:
batch_size = 32
model.fit(X_train, y_train, epochs = 10, batch_size=batch_size)

Epoch 1/10
127/127 [==============================] - 11s 76ms/step - loss: 1.6686 - accuracy: 0.3269
Epoch 2/10
127/127 [==============================] - 9s 75ms/step - loss: 1.6639 - accuracy: 0.3316
Epoch 3/10
127/127 [==============================] - 10s 75ms/step - loss: 1.6585 - accuracy: 0.3316
Epoch 4/10
127/127 [==============================] - 9s 75ms/step - loss: 1.6613 - accuracy: 0.3316
Epoch 5/10
127/127 [==============================] - 9s 75ms/step - loss: 1.6611 - accuracy: 0.3291
Epoch 6/10
127/127 [==============================] - 10s 75ms/step - loss: 1.6611 - accuracy: 0.3319
Epoch 7/10
127/127 [==============================] - 10s 76ms/step - loss: 1.6580 - accuracy: 0.3351
Epoch 8/10
127/127 [==============================] - 10s 76ms/step - loss: 1.6563 - accuracy: 0.3370
Epoch 9/10
127/127 [==============================] - 10s 75ms/step - loss: 1.6579 - accuracy: 0.3358
Epoch 10/10
127/127 [==============================] - 10s 82ms/step - loss: 1.6564 -

In [135]:
score = model.evaluate(X_test, y_test, verbose = 1, batch_size = batch_size)
print("Accuracy: %.2f" % (score[1]*100))

32/32 [==============================] - 1s 17ms/step - loss: 1.6474 - accuracy: 0.3363
Accuracy: 33.63


In [136]:
test = data['Text'][0]
test = text_cleaning(test)
test = test.replace('rt ','')
test = [test]
test = tokenizer.texts_to_sequences(test)
test = pad_sequences(test, maxlen=24, padding = 'post')

In [138]:
class_label = model.predict_classes(test)
print(le.inverse_transform(class_label))

AttributeError: ignored

In [139]:
np.argmax(model.predict(test), axis=-1)

ValueError: ignored

### CNN-RNN and CNN-LSTM

In [140]:
# Convolution
kernel_size = 5
filters = 64
pool_size = 4

In [141]:
model = Sequential()
model.add(Embedding(max_features, embed_dim,input_length = X.shape[1]))
model.add(Dropout(0.2))
model.add(Conv1D(filters,
                 kernel_size,
                 padding='valid',
                 activation='relu',
                 strides=1))
model.add(MaxPooling1D(pool_size=pool_size))
model.add(LSTM(hidden_layer))
model.add(Dense(6))
model.add(Activation('sigmoid'))

In [142]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [143]:
batch_size = 32
model.fit(X_train, y_train, epochs = 15, batch_size=batch_size)

Epoch 1/15
127/127 [==============================] - 18s 114ms/step - loss: 1.6608 - accuracy: 0.3286
Epoch 2/15
127/127 [==============================] - 14s 114ms/step - loss: 1.4441 - accuracy: 0.4310
Epoch 3/15
127/127 [==============================] - 15s 114ms/step - loss: 1.1309 - accuracy: 0.5929
Epoch 4/15
127/127 [==============================] - 14s 113ms/step - loss: 0.9127 - accuracy: 0.6842
Epoch 5/15
127/127 [==============================] - 14s 112ms/step - loss: 0.7636 - accuracy: 0.7473
Epoch 6/15
127/127 [==============================] - 15s 114ms/step - loss: 0.5791 - accuracy: 0.8164
Epoch 7/15
127/127 [==============================] - 14s 114ms/step - loss: 0.4879 - accuracy: 0.8495
Epoch 8/15
127/127 [==============================] - 15s 115ms/step - loss: 0.4304 - accuracy: 0.8668
Epoch 9/15
127/127 [==============================] - 14s 114ms/step - loss: 0.3732 - accuracy: 0.8897
Epoch 10/15
127/127 [==============================] - 14s 114ms/step - l

In [144]:
score = model.evaluate(X_test, y_test, verbose = 1, batch_size = batch_size)
print("Accuracy: %.2f" % (score[1]*100))

32/32 [==============================] - 1s 24ms/step - loss: 2.3800 - accuracy: 0.5207
Accuracy: 52.07


### Using word2vec in Keras 

In [146]:
#Reading the data
data = pd.read_excel('/content/drive/MyDrive/model_imp_NLP/be_data_no_un_combined.xlsx')

In [ ]:
# def clean_data(tweet):
#     x = re.sub("[^a-zA-Z0-9]", " ",tweet) 
#     x = x.lower().split()                             
#     stops = set(stopwords.words("english"))                  
#     words = [w for w in x if not w in stops] 
#     return( " ".join(words)) 

In [ ]:
# data['text'] = data['text'].apply(lambda x: clean_data(x))

# for i in range(len(data)):
#     data['text'][i] = data['text'][i].replace('rt ','')

In [148]:
'''
Text Cleaning
'''
def text_cleaning(row):
  # to remove HTML tags
  text = BeautifulSoup(row, 'html.parser').get_text()
  d = re.sub(r'(https|http)?:\/\/(\w|\.|\/|\?|\=|\&|\%)*\b', '', text, flags=re.MULTILINE) #This line is for removing url
  post = d.replace('\n', '')
  post = post.replace('—', ' ')
  # to remove accented characters
  new_text = unicodedata.normalize('NFKD', post).encode('ascii', 'ignore').decode('utf-8', 'ignore')
  # to remove special characters and numbers
  # define the pattern to keep
  #pat = r'[^a-zA-z0-9.,!?/:;\"\'\s]' 
  #text = re.sub(pat, '', new_text)
  #to remove punctuation
  text = ''.join([c for c in text if c not in string.punctuation])
  # to remove special characters
  pattern = r'^\s*|\s\s*'
  text = re.sub(pattern, ' ', text).strip()
  # convert into lower case
  text = text.lower() 
  # Stopword Removing
  tokenizer = ToktokTokenizer()
  # convert sentence into token of words
  tokens = tokenizer.tokenize(text)
  tokens = [token.strip() for token in tokens]
  # check in lowercase 
  #t = [token for token in tokens if token.lower() not in stopword_list]
  #text = ' '.join(t) 
  # Stemming
  #t = [stemming.stem(token) for token in tokens ]
  #text = ' '.join(t) 

  return text

In [149]:
def get_becodemixed_stop_words():
    #swdf1 = pd.read_csv("/content/drive/MyDrive/automated_tamil_text_classification-master/data/TamilNLP_TamilStopWords.txt",  header=None) 
    swdf2 = pd.read_csv("/content/drive/MyDrive/mode_imp_AED 25GPU/custom_becodemixed_stopwords.txt",  header=None) 
    #sw1 = swdf1[0].tolist()
    sw2 = swdf2[0].tolist()
    #tamil_stop_words = list(set(sw1 + sw2))
    becodemixed_stop_words = list(sw2)
    return becodemixed_stop_words

In [150]:
becodemixed_stop_words = get_becodemixed_stop_words()
data['Texts'] = data['Text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (becodemixed_stop_words)]))



data['cleaned'] = data['Texts'].apply(text_cleaning)



## Data samples after cleaning
print("Original Data:===\n",data.Text[0],"\nCleaned Data:===\n",data.cleaned[0],)

Original Data:===
  Dakhachish ai to tui svf are chala..to jeet dar collection to fake blban e to ... sir manush boka noi 
Cleaned Data:===
 dakhachish tui svf are chalato jeet dar collection fake blban sir manush boka noi


In [151]:
reviews = data['Text'].tolist()
sentiment = data['Label'].tolist()

corpus = []
for i in range(len(reviews)):
    corpus.append(word_tokenize(reviews[i]))

In [152]:
wv_model = Word2Vec(corpus, size=100, window=5, min_count=1)
w2v_model_wv = wv_model.wv

In [154]:
#Tokenization
max_features = 1200 #number of words to keep. 1200 is the number of unique words in the corpus.
tokenizer = Tokenizer(nb_words=max_features, split=' ')
tokenizer.fit_on_texts(data['Text'].values)
X = tokenizer.texts_to_sequences(data['Text'].values)
X = pad_sequences(X, padding = 'post') #Zero padding at the end of the sequence
word_index = tokenizer.word_index

In [157]:
maxlen = len(X[0])

In [158]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
print('Shape of X_train and X_test data:', X_train.shape,X_test.shape)
print('Shape of y_train and y_test:', y_train.shape,y_test.shape)

Shape of X_train and X_test data: (4053, 79) (1014, 79)
Shape of y_train and y_test: (4053, 6) (1014, 6)


In [159]:
nb_words = len(wv_model.wv.vocab)
embedding_dimension = 100

embedding_matrix = np.zeros((nb_words, embedding_dimension))
for word, i in word_index.items():
    if word in wv_model.wv.vocab:
        embedding_matrix[i] = wv_model.wv[word]

In [160]:
wv_layer = Embedding(nb_words,embedding_dimension,weights=[embedding_matrix], input_length=maxlen,
                     trainable=True)
input_tweet = Input(shape=(maxlen,))
embedded_sequences = wv_layer(input_tweet)
x = SimpleRNN(64, return_sequences=False)(embedded_sequences)
preds = Dense(6, activation='sigmoid')(x)

In [161]:
model = Model(inputs=[input_tweet], outputs=preds)

In [162]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [163]:
model.fit([X_train], y_train, validation_split=0.1,epochs=10, batch_size=256, shuffle=True)

Epoch 1/10
15/15 [==============================] - 3s 110ms/step - loss: 1.6815 - accuracy: 0.3205 - val_loss: 1.6372 - val_accuracy: 0.3325
Epoch 2/10
15/15 [==============================] - 1s 88ms/step - loss: 1.6522 - accuracy: 0.3411 - val_loss: 1.6287 - val_accuracy: 0.3325
Epoch 3/10
15/15 [==============================] - 1s 89ms/step - loss: 1.6536 - accuracy: 0.3411 - val_loss: 1.6317 - val_accuracy: 0.3325
Epoch 4/10
15/15 [==============================] - 1s 89ms/step - loss: 1.6528 - accuracy: 0.3411 - val_loss: 1.6364 - val_accuracy: 0.3325
Epoch 5/10
15/15 [==============================] - 1s 88ms/step - loss: 1.6510 - accuracy: 0.3411 - val_loss: 1.6268 - val_accuracy: 0.3325
Epoch 6/10
15/15 [==============================] - 2s 124ms/step - loss: 1.6470 - accuracy: 0.3411 - val_loss: 1.6434 - val_accuracy: 0.3202
Epoch 7/10
15/15 [==============================] - 3s 188ms/step - loss: 1.6544 - accuracy: 0.3307 - val_loss: 1.6301 - val_accuracy: 0.3325
Epoch 8/10

In [164]:
score = model.evaluate(X_test, y_test, verbose = 2, batch_size = batch_size)
print("Accuracy: %.2f" % (score[1]*100))

32/32 - 0s - loss: 1.7422 - accuracy: 0.2890 - 439ms/epoch - 14ms/step
Accuracy: 28.90
